project:
  - title: Virtual Try-on
    image: vto_demo.png
    detail: >
      <p>Launching a virtual try-on service</p>
      
      <img src='site.baseurl/assets/images/project_detail/vto_demo.png' class='img-responsive' alt='keyscreen of our system'>
      
      <p style='text-align: center;'><b>Our web-based demo system to experience virtual try-on service</b></p>

      <hr>

      <p><b>[My role in this project]</b><br>Conducting market research and interview, defining key features of an web application, creating user journey and interface layouts, developing an internal tool and a pipeline to create training and test dataset for the AI architecture.</p>
    tags:
      - Research
      - Service
      - AI
      - Design
    description: >-
      Launching a virtual try-on service
    id: virtual_try_on
  - title: AI Avatar Profile
    image: avatar_profile.png
    detail: >
      <p>By launching an AI avatar profile service, user acquisition rate has been increased by 92% and achieved 75% reach rate.</p>
      
      <img src='site.baseurl/assets/images/project_detail/avatar_profile.png' class='img-responsive' alt='AI avatar profile images generated by our pipeline'>
      
      <p style='text-align: center;'><b>AI avatar profile images generated by our pipeline</b></p>

      <hr>

      <p><b>[My role in this project]</b><br>Designing 900 prompt templates for figure and background, performing thematic analysis to quantify and interpret responses.</p>
    tags:
      - Research
      - Service
      - AI-generated avatar
      - Synthetic data
    description: >-
      Launching an avatar profile generation system using AI
  - title: Synthetic Data Pipeline for AI Architectures
    image: synthetic_data.png
    detail: >
      <p>Creating a synthetic data generation pipeline for human pose and facial expression recognition models</p>
      
      <img src='site.baseurl/assets/images/project_detail/synthetic_data.png' class='img-responsive' alt='Synthetic data generation images'>
      
      <p style='text-align: center;'><b>Examples of synthetic training data generated by our pipeline</b></p>

      <hr>

      <p><b>[My role in this project]</b><br>Interviewing AI engineers and animation graphic designers to understand the limitation of current data generation systems. Building training datasets worth $360,000</p>
    tags:
      - Research
      - Service
      - Synthetic data
      - Facial expression
      - Motion
    description: >-
      Creating a synthetic data generation pipeline for human pose and facial expression recognition models
  - title: User Satisfaction on 3D Avatar Facial Expression
    image: facial_expression.png
    detail: >
      <p>Understanding how people perceive 3D avatar facial expression features</p>
      
      <img src='site.baseurl/assets/images/project_detail/facial_expression.png' class='img-responsive' alt='Facial expression'>
      
      <p style='text-align: center;'><b>Examples of synthetic training data generated by our pipeline</b></p>

      <hr>

      <p><b>[My role in this project]</b><br>Designing and conducting a survey and focus group interviews to investigate characteristics of 3D avatar facial expression</p>
    tags:
      - Research
      - Service
      - AI-generated avatar
      - Facial expression
    description: >-
      Understanding how people perceive 3D avatar facial expression features
  - title: An Empirical Study on How People Perceive AI-generated Music
    image: cikm2022_music.png
    paper: cikm2022_music_paper.pdf
    detail: >
      <p>Proposing qualitative evaluation metrics to assess human satisfaction on AI-generated music</p>
      
      <img src='site.baseurl/assets/images/project_detail/cikm2022_music.png' class='img-responsive' alt='Human perception on AI-generated music'>
      
      <p style='text-align: center;'><b>Satisfaction with AI-generated music (1–7 Likert scale)</b></p>

      <hr>

      <p><b>[My role in this project]</b><br>Leading the project</p>
    tags:
      - Research
      - <i class='fas fa-book'></i>&nbsp; CIKM '22
      - Human-AI Collaboration
      - Music
      - Evaluation
    description: >-
      Proposing qualitative evaluation metrics to assess human satisfaction on AI-generated music
  - title: A Visual Analytics System for Improving Attention-based Traffic Forecasting Models
    image: tvcg2023_analytics.png
    paper: tvcg2023_analytics_paper.pdf
    detail: >
      <p>Designing a system that allow users to explore how AI architectures make prediction</p>

      <img src='site.baseurl/assets/images/project_detail/tvcg2023_analytics.png' class='img-responsive' alt='Visual Analytics System'>
      
      <p style='text-align: center;'><b>Our system for analyzing how an attention-based deep learning model predicts traffic congestion</b></p>

      <hr>

      <p><b>[My role in this project]</b><br>Executing some case studies to inverstigate user journey and identify the features of a visual analytics system</p>
    tags:
      - Research
      - <i class='fas fa-book'></i>&nbsp; TVCG '23
      - Forecasting
      - AI
      - Spatiotemporal data
      - Visual analytics system
    description: >-
      Designing a system that allow users to explore how AI architectures make prediction
  - title: Learning to Remember Patterns - Pattern Matching Memory Networks for Traffic Forecasting
    image: iclr2022_pattern.png
    paper: iclr2022_pattern_paper.pdf
    detail: >
      <p>Suggesting a forecasting architecture under complex spatio-temporal condition</p>
      
      <img src='site.baseurl/assets/images/project_detail/iclr2022_pattern.png' class='img-responsive' alt='Learning to Remember Patterns'>
      
      <p style='text-align: center;'><b>Multiple traffic data with similar pattern and the extracted representative pattern</b></p>

      <hr>

      <p><b>[My role in this project]</b><br>Executing qualitative research to identify user pain points and behavior patterns</p>
    tags:
      - Research
      - <i class='fas fa-book'></i>&nbsp; ICLR '22
      - Forecasting
      - AI
      - Spatiotemporal data
    description: >-
      Suggesting a forecasting architecture under complex spatiotemporal condition
  - title: Wait, Let’s Think about Your Purchase Again - A Study on Interventions for Supporting Self-Controlled Online Purchases
    image: www2021_purchase.png
    paper: www2021_purchase_paper.pdf
    detail: >
      <p>Investigating users' impulse buying behaviors and self-control strategies</p>
      
      <img src='site.baseurl/assets/images/project_detail/www2021_purchase.png' class='img-responsive' alt='Purchase Intervention'>
      
      <p style='text-align: center;'><b>Four types of interventions: (A) Reflection; (B) Distraction; (C) Desire Reduction; (D) Salient Cost</b></p>

      <hr>

      <p><b>[My role in this project]</b><br>Conducting user surveys and interviews to identify user pain points and understand their behavior patterns. Investigating the experiment result by thematic analysis</p>
    tags:
      - Research
      - <i class='fas fa-book'></i>&nbsp; WWW '21
      - Human-computer interaction
      - User behavior
      - Social computing
    description: >-
      Investigating users' impulse buying behaviors and self-control strategies
  - title: An Empirical Experiment on Deep Learning Models for Predicting Traffic Data
    image: icde2021_traffic.png
    paper: icde2021_traffic_paper.pdf
    detail: >
      <p>Analyzing the performance of traffic forecasting architectures</p>
      
      <img src='site.baseurl/assets/images/project_detail/icde2021_traffic.png' class='img-responsive' alt='Traffic Forecasting'>
      
      <p style='text-align: center;'><b>Different models show varying accuracy performance based on traffic data dynamics</b></p>

      <hr>

      <p><b>[My role in this project]</b><br>Conducting user surveys and interviews to identify user pain points and understand their behavior patterns. Investigating the experiment result by thematic analysis</p>
    tags:
      - Research
      - <i class='fas fa-book'></i>&nbsp; ICDE '21
      - Forecasting
      - AI
      - Spatiotemporal data
    description: >-
      Analyzing the performance of traffic forecasting architectures


      

    
